"""empty message

Revision ID: 0c98cc8f524a
Revises: 1ef1df7469de
Create Date: 2020-09-18 14:10:41.344450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c98cc8f524a'
down_revision = '1ef1df7469de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'end_date')
    # ### end Alembic commands ###
