"""add User

Revision ID: 1e3561fa5156
Revises: e4ca7baacf44
Create Date: 2020-09-27 11:12:10.751707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3561fa5156'
down_revision = 'e4ca7baacf44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('student', 'teachers_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'teachers_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user')
    # ### end Alembic commands ###
