"""empty message

Revision ID: 378cf529d23b
Revises: 4de66df6f208
Create Date: 2020-09-22 10:22:46.763072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378cf529d23b'
down_revision = '4de66df6f208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'image_url')
    op.drop_column('exam', 'image_url')
    # ### end Alembic commands ###
