"""empty message

Revision ID: 4de66df6f208
Revises: 0c98cc8f524a
Create Date: 2020-09-21 14:11:58.892817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de66df6f208'
down_revision = '0c98cc8f524a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'result', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'teacher_id')
    # ### end Alembic commands ###
