"""relate exams-groups

Revision ID: 968b35414be3
Revises: d0062f49b535
Create Date: 2020-09-24 12:59:55.152741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968b35414be3'
down_revision = 'd0062f49b535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'image_url')
    op.add_column('group', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'exam', ['exam_id'], ['id'])
    op.alter_column('student', 'teachers_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'teachers_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'exam_id')
    op.add_column('exam', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
