"""relate group-year

Revision ID: 975fa69c9789
Revises: 2be07d655d83
Create Date: 2020-09-23 12:15:02.560417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975fa69c9789'
down_revision = '2be07d655d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('school_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'schoolyear', ['school_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'school_year_id')
    # ### end Alembic commands ###
