"""add sub&year to ques

Revision ID: d0062f49b535
Revises: 975fa69c9789
Create Date: 2020-09-23 19:55:01.757736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0062f49b535'
down_revision = '975fa69c9789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'subject', ['subject_id'], ['id'])
    op.add_column('question', sa.Column('answer1_image_url', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('answer2_image_url', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('answer3_image_url', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('correct_answer_image_url', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('school_year_id', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'question', 'schoolyear', ['school_year_id'], ['id'])
    op.add_column('student', sa.Column('teachers_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'teachers_num')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'subject_id')
    op.drop_column('question', 'school_year_id')
    op.drop_column('question', 'correct_answer_image_url')
    op.drop_column('question', 'answer3_image_url')
    op.drop_column('question', 'answer2_image_url')
    op.drop_column('question', 'answer1_image_url')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'subject_id')
    # ### end Alembic commands ###
