"""update examRoom

Revision ID: e2eaf2e01df3
Revises: 378cf529d23b
Create Date: 2020-09-22 17:01:36.667208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2eaf2e01df3'
down_revision = '378cf529d23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_room', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_constraint('exam_room_group_id_fkey', 'exam_room', type_='foreignkey')
    op.create_foreign_key(None, 'exam_room', 'student', ['student_id'], ['id'])
    op.drop_column('exam_room', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_room', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_room', type_='foreignkey')
    op.create_foreign_key('exam_room_group_id_fkey', 'exam_room', 'group', ['group_id'], ['id'])
    op.drop_column('exam_room', 'student_id')
    # ### end Alembic commands ###
