"""relate exams-groups2

Revision ID: e4ca7baacf44
Revises: 968b35414be3
Create Date: 2020-09-24 13:28:47.990620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ca7baacf44'
down_revision = '968b35414be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('exam_id', 'group_id')
    )
    op.drop_constraint('group_exam_id_fkey', 'group', type_='foreignkey')
    op.drop_column('group', 'exam_id')
    op.alter_column('student', 'teachers_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'teachers_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('group', sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('group_exam_id_fkey', 'group', 'exam', ['exam_id'], ['id'])
    op.drop_table('group_exam')
    # ### end Alembic commands ###
